name = "jwt-ratelimiter"
main = "src/index.js"
compatibility_date = "2024-06-21"

durable_objects = { bindings = [{ name = "RateLimiter", class_name = "RateLimiter" }] }

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]

routes = [
  { pattern = "hassio.42junebug.com/*", script = "jwt-ratelimiter" }
]